version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"          # direct API access (optional)
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uydrive-api.rule=Host(`cloud.uydrive.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.uydrive-api.entrypoints=websecure"
      - "traefik.http.routers.uydrive-api.tls.certresolver=le"
      - "traefik.http.services.uydrive-api.loadbalancer.server.port=2283"

  immich-web:
    container_name: immich_web
    image: uydrive-web:0.5
    command: ["-c", "npm run dev -- --host 0.0.0.0 --port 3000"]
    restart: always
    networks:
      - default
    labels:
      - "traefik.enable=true"
      # all **non-API** paths hit the UI
      - "traefik.http.routers.uydrive-web.rule=Host(`cloud.uydrive.com`)"
      - "traefik.http.routers.uydrive-web.entrypoints=websecure"
      - "traefik.http.routers.uydrive-web.tls.certresolver=le"
      - "traefik.http.services.uydrive-web.loadbalancer.server.port=3000"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:

networks:
  default:
    name: uydrive_default     # reuse the Traefik network
    external: true
